COMMON_COLUMNS = [
    # "past_appearances",
    "song_name",
    "song_uuid",
    "url",
    "labels",
    "main_artist",
    "main_artist_uuid",
    "main_artist_tiktok_followers",
    "main_artist_spotify_followers",
    "main_artist_spotify_monthly_listeners",
    "main_artist_spotify_conversion_rate",
    "root_genres",
    "instrumentalness",
    "release_date",
    "today_streams",
    "yesterday_streams",
    "this_week_7_day_average",
    "last_week_7_day_average",
    "week_to_week_percentage_increase",
    "day_1-3_average",
    "day_7-9_average",
    "%_increase",
    "14_day_median",
    "14_day_max",
    "total_streams",
]